# Generated by Django 3.0.7 on 2024-03-16 20:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('year', models.IntegerField(blank=True, choices=[(2000, 2000), (2001, 2001), (2002, 2002), (2003, 2003), (2004, 2004), (2005, 2005), (2006, 2006), (2007, 2007), (2008, 2008), (2009, 2009), (2010, 2010), (2011, 2011), (2012, 2012), (2013, 2013), (2014, 2014), (2015, 2015), (2016, 2016), (2017, 2017), (2018, 2018), (2019, 2019), (2020, 2020), (2021, 2021), (2022, 2022), (2023, 2023), (2024, 2024)], null=True, verbose_name='Year')),
                ('price', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('availability', models.CharField(blank=True, max_length=50, null=True)),
                ('delivery', models.CharField(blank=True, max_length=50, null=True)),
                ('documents', models.CharField(blank=True, max_length=50, null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('warranty', models.BooleanField(blank=True, choices=[('1', 'Si'), ('2', 'No')], null=True)),
                ('guarantee', models.CharField(blank=True, max_length=50, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=50, null=True)),
                ('no_of_owners', models.IntegerField(blank=True, choices=[('1', 'Si'), ('2', 'No')], null=True)),
                ('is_featured', models.BooleanField(blank=True, choices=[('1', 'Si'), ('2', 'No')], default=False, null=True)),
                ('created_date', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('passengers', models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], null=True)),
                ('condition', models.CharField(blank=True, max_length=100, null=True)),
                ('obs', models.TextField(blank=True, null=True)),
                ('ref', models.CharField(blank=True, max_length=100, null=True)),
                ('cabin', models.CharField(blank=True, max_length=100, null=True)),
                ('first_registration', models.DateField(blank=True, null=True)),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('driver_side', models.CharField(blank=True, max_length=100, null=True)),
                ('color_ext', models.CharField(blank=True, max_length=100, null=True)),
                ('color_int', models.CharField(blank=True, max_length=100, null=True)),
                ('model', models.CharField(blank=True, max_length=100, null=True)),
                ('kilometrage', models.CharField(blank=True, max_length=100, null=True)),
                ('engine', models.CharField(blank=True, max_length=100, null=True)),
                ('engine_type', models.CharField(blank=True, max_length=100, null=True)),
                ('tacho', models.CharField(blank=True, choices=[('1', 'Digital'), ('2', 'Disco')], max_length=100, null=True)),
                ('width', models.CharField(blank=True, max_length=100, null=True)),
                ('length', models.CharField(blank=True, max_length=100, null=True)),
                ('fuel_capacity', models.CharField(blank=True, max_length=100, null=True)),
                ('transmission', models.CharField(blank=True, choices=[('1', 'Automatico'), ('2', 'Manual'), ('3', 'Semi-automatico'), ('4', 'Semi-manual'), ('5', 'Mecanico'), ('6', 'Semi-mecanico'), ('7', 'Mecanico-automatico'), ('8', 'Mecanico-semi-automatico'), ('9', 'Mecanico-semi-manual')], max_length=100, null=True)),
                ('fifth_wheel_height', models.CharField(blank=True, max_length=100, null=True)),
                ('qty_of_deposits', models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], null=True)),
                ('qty_of_gears', models.IntegerField(blank=True, choices=[(5, '5'), (6, '6'), (8, '8'), (10, '10'), (12, '12')], null=True)),
                ('height', models.CharField(blank=True, max_length=100, null=True)),
                ('axis_distance', models.CharField(blank=True, max_length=100, null=True)),
                ('axis_one_distance', models.CharField(blank=True, max_length=100, null=True)),
                ('axis_one_breaks', models.CharField(blank=True, max_length=100, null=True)),
                ('axis_one_suspension', models.CharField(blank=True, choices=[('1', 'Parabolica'), ('2', 'Neumática'), ('3', 'Muelles'), ('4', 'Pneumática'), ('5', 'Ballestas'), ('6', 'Eje rígido')], max_length=100, null=True)),
                ('axis_one_weight', models.CharField(blank=True, max_length=100, null=True)),
                ('axis_one_percentage', models.CharField(blank=True, choices=[('1', '10 %'), ('2', '20 %'), ('3', '30 %'), ('4', '40 %'), ('5', '50 %'), ('6', '60 %'), ('7', '70 %'), ('8', '80 %'), ('9', '90 %')], max_length=100, null=True)),
                ('axis_two_distance', models.CharField(blank=True, max_length=100, null=True)),
                ('axis_two_breaks', models.CharField(blank=True, max_length=100, null=True)),
                ('axis_two_suspension', models.CharField(blank=True, choices=[('1', 'Parabolica'), ('2', 'Neumática'), ('3', 'Muelles'), ('4', 'Pneumática'), ('5', 'Ballestas'), ('6', 'Eje rígido')], max_length=100, null=True)),
                ('axis_two_weight', models.CharField(blank=True, max_length=100, null=True)),
                ('axis_two_percentage', models.CharField(blank=True, choices=[('1', '10 %'), ('2', '20 %'), ('3', '30 %'), ('4', '40 %'), ('5', '50 %'), ('6', '60 %'), ('7', '70 %'), ('8', '80 %'), ('9', '90 %')], max_length=100, null=True)),
                ('drive_train', models.CharField(blank=True, choices=[('1', 'hidráulico'), ('2', 'eléctrico'), ('3', 'hidrodinámico'), ('4', 'electromagnético'), ('5', 'neumático'), ('6', '2x1')], max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_videos', models.FileField(blank=True, null=True, upload_to='videos/%Y/%m/%d/')),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='truck_videos', to='cars.Cars')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_photos', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('is_main', models.BooleanField(default=False)),
                ('truck', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='truck_photos', to='cars.Cars')),
            ],
        ),
        migrations.CreateModel(
            name='Intern_cabin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intern_extras', models.ManyToManyField(blank=True, to='cars.Accessory')),
            ],
        ),
        migrations.CreateModel(
            name='Extras_security',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extras_security', models.ManyToManyField(blank=True, to='cars.Accessory')),
            ],
        ),
        migrations.CreateModel(
            name='Ext_extras',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ext_extras', models.ManyToManyField(blank=True, to='cars.Accessory')),
            ],
        ),
    ]
