# Generated by Django 3.0.7 on 2024-03-17 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_auto_20240316_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cars',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Fabricante'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='cabin',
            field=models.CharField(blank=True, choices=[('1', 'Cabina Normal'), ('2', 'Cabina con Litera'), ('3', 'Cabina Alta'), ('4', 'Cabina Baja'), ('5', 'Cabina Extra-Ancha'), ('6', 'Cabina Confort'), ('7', 'Cabina Dormitorio'), ('8', 'Cabina Doble'), ('9', 'Cabina Corta'), ('10', 'Cabina Modular')], max_length=100, null=True, verbose_name='Tipo de cabina'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='color_ext',
            field=models.CharField(blank=True, choices=[('1', 'Blanco'), ('2', 'Negro'), ('3', 'Gris'), ('4', 'Rojo'), ('5', 'Amarillo'), ('6', 'Verde'), ('7', 'Azul'), ('8', 'Naranja'), ('9', 'Rosa'), ('10', 'Marrón'), ('11', 'Plata')], max_length=100, null=True, verbose_name='Color externo'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='color_int',
            field=models.CharField(blank=True, choices=[('1', 'Blanco'), ('2', 'Negro'), ('3', 'Gris'), ('4', 'Rojo'), ('5', 'Amarillo'), ('6', 'Verde'), ('7', 'Azul'), ('8', 'Naranja'), ('9', 'Rosa'), ('10', 'Marrón'), ('11', 'Plata')], max_length=100, null=True, verbose_name='Color interno'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='driver_side',
            field=models.CharField(blank=True, choices=[('1', 'Izquierda'), ('12', 'Derecha')], max_length=100, null=True, verbose_name='Lado del conductor'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='first_registration',
            field=models.DateField(blank=True, null=True, verbose_name='Primera matricula'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='is_featured',
            field=models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Si')], default=False, null=True, verbose_name='Favorito'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='ref',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Referencia'),
        ),
        migrations.AlterField(
            model_name='cars',
            name='warranty',
            field=models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Si')], null=True, verbose_name='Tiene garantia'),
        ),
    ]
