# Generated by Django 3.0.7 on 2024-03-29 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20240329_0859'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Photo',
            new_name='car_photo',
        ),
    ]
