# Generated by Django 3.0.7 on 2024-03-05 13:33

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_auto_20240305_1433'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[], max_length=200, null=True),
        ),
    ]
