# Generated by Django 3.0.7 on 2024-03-05 13:50

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Bluetooth')], max_length=1, null=True),
        ),
    ]
