# Generated by Django 3.0.7 on 2024-03-29 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_auto_20240329_0900'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='car_photo',
            new_name='photo',
        ),
    ]
