# Generated by Django 3.0.7 on 2024-03-06 20:14

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_auto_20240305_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='features',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Bluetooth'), (2, 'ABS'), (3, 'EBD'), (4, 'GPS')], max_length=7, null=True),
        ),
    ]
