# Generated by Django 3.0.7 on 2024-03-06 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_auto_20240306_2114'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='car_photos',
        ),
        migrations.RemoveField(
            model_name='photo',
            name='car_photo',
        ),
        migrations.AddField(
            model_name='photo',
            name='car',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_photo', to='cars.Car'),
        ),
        migrations.AddField(
            model_name='photo',
            name='car_photos',
            field=models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/'),
        ),
    ]
