# Generated by Django 3.0.7 on 2024-03-29 11:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_auto_20240329_1108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='slug',
        ),
        migrations.AddField(
            model_name='car',
            name='beds',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], null=True, verbose_name='Camas'),
        ),
        migrations.AddField(
            model_name='car',
            name='front_tire',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Neumáticos delanteros'),
        ),
        migrations.AddField(
            model_name='car',
            name='rear_tire',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Neumáticos detrás'),
        ),
        migrations.AddField(
            model_name='car',
            name='weels',
            field=models.CharField(blank=True, choices=[('1', '4x2'), ('2', '4x4'), ('3', '4x6'), ('4', '4x8'), ('5', '4x10'), ('6', '4x12')], max_length=100, null=True, verbose_name='Ruedas'),
        ),
        migrations.AlterField(
            model_name='car',
            name='axis_distance',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Distancia entre ejes'),
        ),
        migrations.AlterField(
            model_name='car',
            name='axis_one_breaks',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Frenos del eje uno'),
        ),
        migrations.AlterField(
            model_name='car',
            name='axis_one_distance',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Distancia del eje uno'),
        ),
        migrations.AlterField(
            model_name='car',
            name='axis_one_percentage',
            field=models.CharField(blank=True, choices=[('1', '10 %'), ('2', '20 %'), ('3', '30 %'), ('4', '40 %'), ('5', '50 %'), ('6', '60 %'), ('7', '70 %'), ('8', '80 %'), ('9', '90 %')], max_length=100, null=True, verbose_name='Porcentaje del eje uno'),
        ),
        migrations.AlterField(
            model_name='car',
            name='axis_one_suspension',
            field=models.CharField(blank=True, choices=[('1', 'Parabolica'), ('2', 'Neumática'), ('3', 'Muelles'), ('4', 'Pneumática'), ('5', 'Ballestas'), ('6', 'Eje rígido')], max_length=100, null=True, verbose_name='Suspensión del eje uno'),
        ),
        migrations.AlterField(
            model_name='car',
            name='axis_one_weight',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Peso del eje uno'),
        ),
        migrations.AlterField(
            model_name='car',
            name='axis_two_breaks',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Frenos del eje dos'),
        ),
        migrations.AlterField(
            model_name='car',
            name='axis_two_distance',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Distancia del eje dos'),
        ),
        migrations.AlterField(
            model_name='car',
            name='axis_two_percentage',
            field=models.CharField(blank=True, choices=[('1', '10 %'), ('2', '20 %'), ('3', '30 %'), ('4', '40 %'), ('5', '50 %'), ('6', '60 %'), ('7', '70 %'), ('8', '80 %'), ('9', '90 %')], max_length=100, null=True, verbose_name='Porcentaje del eje dos'),
        ),
        migrations.AlterField(
            model_name='car',
            name='axis_two_suspension',
            field=models.CharField(blank=True, choices=[('1', 'Parabolica'), ('2', 'Neumática'), ('3', 'Muelles'), ('4', 'Pneumática'), ('5', 'Ballestas'), ('6', 'Eje rígido')], max_length=100, null=True, verbose_name='Suspensión del eje dos'),
        ),
        migrations.AlterField(
            model_name='car',
            name='axis_two_weight',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Peso del eje dos'),
        ),
        migrations.AlterField(
            model_name='car',
            name='brand',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca'),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='car',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Ciudad'),
        ),
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(blank=True, choices=[('1', 'Blanco'), ('2', 'Negro'), ('3', 'Gris'), ('4', 'Rojo'), ('5', 'Amarillo'), ('6', 'Verde'), ('7', 'Azul'), ('8', 'Naranja'), ('9', 'Rosa'), ('10', 'Marrón'), ('11', 'Plata')], max_length=100, null=True, verbose_name='Color exterior'),
        ),
        migrations.AlterField(
            model_name='car',
            name='color_int',
            field=models.CharField(blank=True, choices=[('1', 'Blanco'), ('2', 'Negro'), ('3', 'Gris'), ('4', 'Rojo'), ('5', 'Amarillo'), ('6', 'Verde'), ('7', 'Azul'), ('8', 'Naranja'), ('9', 'Rosa'), ('10', 'Marrón'), ('11', 'Plata')], max_length=100, null=True, verbose_name='Color interior'),
        ),
        migrations.AlterField(
            model_name='car',
            name='created_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True, verbose_name='Fecha de registro'),
        ),
        migrations.AlterField(
            model_name='car',
            name='drive_train',
            field=models.CharField(blank=True, choices=[('1', 'hidráulico'), ('2', 'eléctrico'), ('3', 'hidrodinámico'), ('4', 'electromagnético'), ('5', 'neumático')], max_length=100, null=True, verbose_name='Tipo de tracción'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Motor'),
        ),
        migrations.AlterField(
            model_name='car',
            name='engine_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Tipo de motor'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fifth_wheel_height',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Altura de la quinta rueda'),
        ),
        migrations.AlterField(
            model_name='car',
            name='first_registration',
            field=models.DateField(blank=True, null=True, verbose_name='Primera matriculación'),
        ),
        migrations.AlterField(
            model_name='car',
            name='fuel_capacity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Capacidad de combustible'),
        ),
        migrations.AlterField(
            model_name='car',
            name='guarantee',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Duración de la garantía'),
        ),
        migrations.AlterField(
            model_name='car',
            name='height',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Altura'),
        ),
        migrations.AlterField(
            model_name='car',
            name='is_featured',
            field=models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Si')], default=False, null=True, verbose_name='Destacado'),
        ),
        migrations.AlterField(
            model_name='car',
            name='kilometrage',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kilometraje'),
        ),
        migrations.AlterField(
            model_name='car',
            name='length',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Modelo'),
        ),
        migrations.AlterField(
            model_name='car',
            name='no_of_owners',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5 +')], null=True, verbose_name='Propietarios'),
        ),
        migrations.AlterField(
            model_name='car',
            name='passengers',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6')], null=True, verbose_name='Pasajeros'),
        ),
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Precio'),
        ),
        migrations.AlterField(
            model_name='car',
            name='qty_of_deposits',
            field=models.IntegerField(blank=True, choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4')], null=True, verbose_name='Cantidad de depósitos'),
        ),
        migrations.AlterField(
            model_name='car',
            name='qty_of_gears',
            field=models.IntegerField(blank=True, choices=[(5, '5'), (6, '6'), (8, '8'), (10, '10'), (12, '12')], null=True, verbose_name='Cantidad de marchas'),
        ),
        migrations.AlterField(
            model_name='car',
            name='tacho',
            field=models.CharField(blank=True, choices=[('1', 'Digital'), ('2', 'Disco')], max_length=100, null=True, verbose_name='Tacógrafo'),
        ),
        migrations.AlterField(
            model_name='car',
            name='transmission',
            field=models.CharField(blank=True, choices=[('1', 'Automatico'), ('2', 'Manual'), ('3', 'Semi-automatico'), ('4', 'Semi-manual'), ('5', 'Mecanico'), ('6', 'Semi-mecanico'), ('7', 'Mecanico-automatico'), ('8', 'Mecanico-semi-automatico'), ('9', 'Mecanico-semi-manual')], max_length=100, null=True, verbose_name='Transmisión'),
        ),
        migrations.AlterField(
            model_name='car',
            name='warranty',
            field=models.BooleanField(blank=True, choices=[(False, 'No'), (True, 'Si')], null=True, verbose_name='Tiene garantía'),
        ),
        migrations.AlterField(
            model_name='car',
            name='width',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Anchura'),
        ),
    ]
