# Generated by Django 3.0.7 on 2024-03-07 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_auto_20240306_2144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='car',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_photos', to='cars.Car'),
        ),
    ]
