# Generated by Django 3.0.7 on 2024-03-07 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_auto_20240307_0537'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
