# Generated by Django 3.0.7 on 2024-03-29 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0009_auto_20240329_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='slug',
            field=models.SlugField(default=1, max_length=1024),
            preserve_default=False,
        ),
    ]
