# Generated by Django 3.0.7 on 2024-03-29 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0010_car_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='slug',
        ),
    ]
