# Generated by Django 3.0.7 on 2024-03-29 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0011_remove_car_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='truck',
            field=models.ManyToManyField(related_name='accessories', to='cars.Car'),
        ),
    ]
