# Generated by Django 3.0.7 on 2024-03-29 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0012_accessory_truck'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extras_security',
            name='extras_security',
        ),
        migrations.RemoveField(
            model_name='intern_cabin',
            name='intern_extras',
        ),
        migrations.RenameField(
            model_name='accessory',
            old_name='truck',
            new_name='cars',
        ),
        migrations.AddField(
            model_name='accessory',
            name='extras_categories',
            field=models.CharField(choices=[('1', 'Seguridad'), ('2', 'Confort'), ('3', 'Calidad'), ('4', 'Servicios')], default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='car',
            name='drive_train',
            field=models.CharField(blank=True, choices=[('1', 'hidráulico'), ('2', 'eléctrico'), ('3', 'hidrodinámico'), ('4', 'electromagnético'), ('5', 'neumático')], max_length=100, null=True, verbose_name='Tipo de retarder'),
        ),
        migrations.DeleteModel(
            name='Ext_extras',
        ),
        migrations.DeleteModel(
            name='Extras_security',
        ),
        migrations.DeleteModel(
            name='Intern_cabin',
        ),
    ]
