# Generated by Django 3.0.7 on 2024-03-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0013_auto_20240329_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='Accessory',
            field=models.ManyToManyField(blank=True, to='cars.Accessory'),
        ),
    ]
