# Generated by Django 3.0.7 on 2024-03-29 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0014_car_accessory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='Accessory',
            field=models.ManyToManyField(blank=True, to='cars.Accessory', verbose_name='Accesorios'),
        ),
        migrations.AlterField(
            model_name='car',
            name='body_style',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Estilo'),
        ),
    ]
